Feature/setup
Tekhlay/hello-react-front-end pull request #1
Opened 2023-06-08 18:19 UTC by Tekhlay

### Milestone 💪 

- [x] Create a new React app called 'hello-react-front-end'
- [x] Create the App component with react-router.
- [x] Create the Greeting component that will display a greeting. Set it up as a route in your App component.
- [x] Create a store, an action and a reducer that will connect to you API endpont to get the random greeting.
- [x] Display the random greeting in your Greeting component.

2023-06-08 19:47 UTC, Kamba56 commented
Hi @Tekhlay

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly add link to the backend repo in the frontend readme.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-09 20:26 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @Tekhlay, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Gitflow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly check the link to the backend from your frontend PR, it should redirect to the backend repo not the backend PR
- [ ] It is also expected to be added to the frontend README file, not to the frontend PR.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 20:26 UTC, Qoosim commented on src/redux/messageReducer.js
> +
- [ ] Kindly correct your fetch_url to the one that generates the random greetings in your backend. The correct url should `'http://localhost:3000/api/v1/messages/index'` based on what I saw in your route and what I used to test your api in the rails-backend app.

![your-backend](https://github.com/Tekhlay/hello-react-front-end/assets/26597432/dd73ab7a-dab0-4e81-a7f3-78f824f541fe)

2023-06-09 20:26 UTC, Qoosim commented on src/components/Greetings.js
> +  );
- [ ] While trying to run your react app to display the random greetings from your backend, I got blank page. You might need to look into the `cors` in your backend for this to be able to display on another PC

![app-behave-1](https://github.com/Tekhlay/hello-react-front-end/assets/26597432/33ac34b6-8429-4828-9fa3-2892d2aad219)

![app-behave-2](https://github.com/Tekhlay/hello-react-front-end/assets/26597432/1bb9d111-b3f5-4abe-91a3-29df6ff64702)

2023-06-11 13:03 UTC, merged